### ISSUE TITLE
Deleted Epoch 

### ISSUE THREAD

**Issue by omaganatellez** [mauriceaj/CRNNeeg-sleep#1]
Hello

I was using the code as directed by the instructions on the README. I fed the algorithm a total of 720 epochs (a 6 hour recording). When I get the stages labels, the vector is only 704 epochs. Were the missing epochs removed because of artifacts as indicated by the paper? Is there a way to know which ones were deleted to review them visually?

Thank you for your time

**Comment by adlam81** [comment]
Hi,
The missing X epochs will always be the last X epochs of the recording. This has to do with the RNN portion of the model, which requires an input of 16 minutes.  So, depending on the length of the recording, no more than the last 16 minutes should be missing.  In your case, for a 6 hour (360 minute) recording, the first 352 minutes will get sleep scores (360 / 16 = 22.5;  22*16 = 352).  This corresponds to the 704 sleep epochs that were labeled.  The final 8 minutes of the recording (0.5*16) will not get labeled, since a full 16 minute epoch is not available.  This corresponds to the missing 16 epochs.  Hope that makes sense.  
Alice

**Comment by omaganatellez** [comment]
Understood, Thank you very much for the quick assist
